# Use Node.js for running frontend tests
FROM node:21

# Set working directory
WORKDIR /usr/src/app

# Copy package.json and install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy the application source code
COPY . .

# Run tests
CMD ["npm", "start"]
