# Use Node.js image for testing
FROM node:21

# Set working directory
WORKDIR /usr/src/app

# Copy package.json and install all dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy the application source code
COPY . .

# Expose the backend port
EXPOSE 8080

# Run tests
CMD ["npm", "start"]
